# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  services:
    app: "http://127.0.0.1:8080"
    auth: "http://auth.production.svc.cluster.local"
    position: "http://position.production.svc.cluster.local"
    push: "http://push.production.svc.cluster.local"
    billing: "http://billing.production.svc.cluster.local"
    modelEngine: "http://model-engine.production.svc.cluster.local"
    modelsManager: "http://models-manager.production.svc.cluster.local"
    web: "http://web.production.svc.cluster.local"
    rcWeb: "http://rc-web.production.svc.cluster.local"
    redis: "redis.production.svc.cluster.local"

image:
  gatewayOld:
    repository: sr2020/eva-gateway
    tag: latest
    pullPolicy: Always
  gateway:
    repository: sr2020/gateway
    tag: latest
    pullPolicy: Always
  nginx:
    repository: sr2020/gateway-nginx
    tag: latest
    pullPolicy: Always

service:
  type: NodePort
  port: 80

# resources
resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi
