language: go

go:
  - "1.13"
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
jobs:
  include:
  - stage: build and push docker image
    script:
      - touch .env
      - export IMAGE_TAG=$(echo "$TRAVIS_COMMIT" | head -c7)
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - make build tag=$IMAGE_TAG
      - make push
      - make build-nginx tag=$IMAGE_TAG
      - make push-nginx

  - stage: deploy production
    install:
      - export IMAGE_TAG=$(echo "$TRAVIS_COMMIT" | head -c7)
      - echo "$SERVICE_ACCOUNT_KEY" | base64 --decode > ${HOME}/service-account-key.json
      - curl https://sdk.cloud.google.com | bash > /dev/null
      - source $HOME/google-cloud-sdk/path.bash.inc
      - gcloud components install kubectl
      - gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=${HOME}/service-account-key.json
      - gcloud container clusters get-credentials prod --project $PROJECT --zone $ZONE
      - kubectl config set-context --current --namespace=production
      - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - helm version
    script:
      - helm upgrade gateway2 helm/gateway2/ --wait --set image.gateway.tag=$IMAGE_TAG --set image.nginx.tag=$IMAGE_TAG
