version: "3.6"

services:
  nginx:
    image: ${IMAGE_NGINX}
    ports:
      - ${NGINX_PORT}:80
    environment:
      APP_HOST: ${APP_HOST}
      AUTH_HOST: ${AUTH_HOST}
      BILLING_HOST: ${BILLING_HOST}
      POSITION_HOST: ${POSITION_HOST}
      MODELS_MANAGER_HOST: ${MODELS_MANAGER_HOST}
      MODEL_ENGINE_HOST: ${MODEL_ENGINE_HOST}
      PUSH_HOST: ${PUSH_HOST}
      WEB_HOST: ${WEB_HOST}
      RC_WEB_HOST: ${RC_WEB_HOST}
      REDIS_HOST: ${REDIS_HOST}
      MAPS_N_MAGIC_HOST: ${MAPS_N_MAGIC_HOST}
    links:
      - app

  app:
    image: ${IMAGE_APP}
    environment:
      APP_PORT: 80
      POSITION_HOST: ${POSITION_HOST}
      JWT_SECRET: ${JWT_SECRET}

  redis:
    image: ${IMAGE_REDIS}

  convey:
    image: ${IMAGE_CONVEY}
    ports:
      - ${CONVEY_PORT}:8080
    environment:
      HOST: http://nginx
      JWT_SECRET: ${JWT_SECRET}
      LOGIN: ${LOGIN}
      PASSWORD: ${PASSWORD}
      MODEL_ID: ${MODEL_ID}
