apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  appHost: {{ .Values.app.services.app | quote }}
  authHost: {{ .Values.app.services.auth | quote }}
  positionHost: {{ .Values.app.services.position | quote }}
  pushHost: {{ .Values.app.services.push | quote }}
  billingHost: {{ .Values.app.services.billing | quote }}
  modelEngineHost: {{ .Values.app.services.modelEngine | quote }}
  modelsManagerHost: {{ .Values.app.services.modelsManager | quote }}
  webHost: {{ .Values.app.services.web | quote }}
  rcWebHost: {{ .Values.app.services.rcWeb | quote }}
  redisHost: {{ .Values.app.services.redis | quote }}
  mapsNMagicHost: {{ .Values.app.services.mapsNMagic | quote }}
  secret: {{ .Values.app.services.secret | quote }}
  positionCache: {{ .Values.app.positionCache | quote }}
