app:
    services:
        secret: ENC[AES256_GCM,data:2VZJCQ==,iv:S7YV9SOZDeQ5BqG3cfG3AYlMEepTQmaEao0JY/KQ4N0=,tag:n6S3P7f90y/zkvYrpz4KwQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/imposing-elixir-249711/locations/global/keyRings/helm-key-ring/cryptoKeys/helm-key
        created_at: '2020-12-05T15:19:31Z'
        enc: CiQAa/qaMDq7f6nBESRPdqCq1xegXJ0Sm3RS4Y+br1BcjRELvD8SSQAUQQCTNCz1H/L66+3GboAQ8Frbz1FlOFbW9DzbLwh9856RE7vOM/uuG34wRVFDVHALssO1NrLJf8auqRLBD2K/yxsZg9olPQE=
    azure_kv: []
    lastmodified: '2020-12-05T15:25:41Z'
    mac: ENC[AES256_GCM,data:6a2vThHJ2xJ9eYLkJ8HGt9+j9hv7b/plcMKt2YAnDzOGh52sEh20wdHDozbor8BymUSI8o9cxl6yA6ddfb5CzM5InbcHnUpCqHJLLgJl6js4WlEk2ASKRkQ+UHKDUVFFpNYuzDhQxNWJUz2ObZ6xhYojUmVsMPBfkFlBh3LucRw=,iv:kLWhc+bE8u6KGv/kWPMpHuHFMvx/LKwFU4fR/arzkqU=,tag:TYIW3qKVcMF/NYI1D+drNg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.3.1
