name: CI

on: [push]

jobs:
  test_production:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.SA_KEY }}
      - run: gcloud components install kubectl
      - run: gcloud container clusters get-credentials prod --project imposing-elixir-249711 --zone europe-west3-b
      - run: kubectl config set-context --current --namespace=production
      - uses: actions/checkout@v1
      - run: 'echo "$TEST_CONFIG" > .env'
        shell: bash
        env:
          TEST_CONFIG: ${{secrets.TEST_CONFIG}}
      - run: |
          echo "JWT_SECRET=" >> .env
          cat .env
          kubectl get secret web2 -o jsonpath="{.data.jwtSecret}" | base64 --decode >> .env
          make test-services
          make test-main
