name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Build & Push gateway to dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sr2020/gateway
          tags: ${{ github.sha }}
          dockerfile: Dockerfile
          username: sr2020
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push nginx to dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sr2020/gateway-nginx
          tags: ${{ github.sha }}
          dockerfile: Dockerfile
          workdir: ./docker
          username: sr2020
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy_rc:
    if: github.ref == 'refs/heads/rc'
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true
          credentials_file_path: /tmp/gcloud-key.json
      - run: gcloud components install kubectl
      - run: gcloud container clusters get-credentials prod --project imposing-elixir-249711 --zone europe-west3-b
      - uses: actions/checkout@v1
      - run: |
          gcloud auth activate-service-account ${{ secrets.SA_EMAIL }} --key-file=/tmp/gcloud-key.json
          kubectl config set-context --current --namespace=production
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm version
          helm plugin install https://github.com/zendesk/helm-secrets
          helm secrets upgrade rc-gateway helm/gateway/ --wait \
            -f helm/gateway/values.yaml \
            -f helm/gateway/values/rc/values.yaml \
            -f helm/gateway/values/rc/secrets.yaml \
            --set image.gateway.tag=$GITHUB_SHA \
            --set image.nginx.tag=$GITHUB_SHA

  test_rc:
    runs-on: ubuntu-20.04
    needs: [deploy_rc]
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "$TEST_CONFIG" > .env'
        shell: bash
        env:
          TEST_CONFIG: ${{secrets.TEST_RC_CONFIG}}
      - run: |
          make test-services
          make test-main

  deploy_production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    needs: [test_rc]
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true
          credentials_file_path: /tmp/gcloud-key.json
      - run: gcloud components install kubectl
      - run: gcloud container clusters get-credentials prod --project imposing-elixir-249711 --zone europe-west3-b
      - uses: actions/checkout@v1
      - run: |
          gcloud auth activate-service-account ${{ secrets.SA_EMAIL }} --key-file=/tmp/gcloud-key.json
          kubectl config set-context --current --namespace=production
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm version
          helm plugin install https://github.com/zendesk/helm-secrets
          helm secrets upgrade gateway-new helm/gateway/ --wait \
            -f helm/gateway/values.yaml \
            -f helm/gateway/values/production/values.yaml \
            -f helm/gateway/values/production/secrets.yaml \
            --set image.gateway.tag=$GITHUB_SHA \
            --set image.nginx.tag=$GITHUB_SHA

  test_production:
    runs-on: ubuntu-20.04
    needs: [deploy_production]
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "$TEST_CONFIG" > .env'
        shell: bash
        env:
          TEST_CONFIG: ${{secrets.TEST_CONFIG}}
      - run: |
          make test-services
          make test-main
