name: CI

on: [push]

jobs:
  test_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo ${{ secrets.TEST_CONFIG }} > .env
          echo "JWT_SECRET=" >> .env
          kubectl get secret web2 -o jsonpath="{.data.jwtSecret}" | base64 --decode >> .env
          make test-services
          make test-main
